// <<< MOVIES >>>
const DATA = [
      {
        id: 1,
        title: "Zootopia",
        desc: "انیمیشنی جذاب درباره شهری پر از حیوانات",
        poster: "zotopia.jpg",
        video:"zotopia.mp4",
        genre: "انیمیشن / کمدی",
        year: "2016",
        rate: "8.0",
        category: "comedy",
        featured: true,
        type: "movie",
      },
      {
        id: 2,
        title: "Hunting Season",
        desc: "در اعماق جنگل های دورافتاده اکلاهما مردی منزوی به نام بودری همراه دخترش لوئیزا زندگی آرام و دور از جامعه ای را میگذرانند اما وقتی آنها زنی مرموز و زخمی به نام ژانویه را از رودخانه نجات میدهند. آرامششان فرو می ریزد. حضور او سایه ای از خطر را به کلبه جنگلیشان میآورد؛ زیرا یک مرد خلافکار بی رحم در تعقیب اوست و برای رسیدن به هدفش از هیچ خشونتی دریغ نمی کنند. حالا بودری باید برای نجات خانواده اش و زنی که به طور ناخواسته وارد زندگیشان شده وارد نبردی بی امان برای بقا شود",
        poster: "sh.jpg",
        video:"hunt.mp4",
        genre: "اکشن",
        year: "2024",
        rate: "8.1",
        category: "action",
        featured: true,
        type: "movie",
      },
      {
        id: 3,
        title: "Percy Jackson",
        desc: "سریال Percy Jackson and the Olympians بر اساس مجموعه ی کتابهای محبوب ریک ریوردان تولید شده است. داستان به تمرکز بر روی پرسی جکسون یک نوجوان خارق العاده",
        poster: "landscape.jpg",
        video:"prc.mp4",
        genre: "فانتزی",
        year: "2023",
        rate: "7",
        category: "fantasy",
        featured: true,
        type: "movie",
      },
      {
        id: 4,
        title: "Running Man",
        desc: "مسابقه‌ای هیجانی",
        poster: "man.jpg",
        video:"man.mp4",
        genre: "Reality / Action",
        year: "2020",
        rate: "7.9",
        category: "action",
        featured: true,
        type: "movie",
      },
      {
        id: 5,
        title: "Wake Up Dead Man",
        desc: "تریلری رازآلود",
        poster: "we.jpg",
        video:"we.mp4",
        genre: "Thriller",
        year: "2024",
        rate: "7.6",
        category: "thriller",
        featured: false,
        type: "movie",
      },
      {
        id: 7,
        title: "13 Days, 13 Nights",
        desc: "در تابستان ۲۰۲۱ وقتی نیروهای آمریکا از افغانستان عقب نشینی میکنند و کابل به دست طالبان سقوط میکند هزاران نفر در جست وجوی فرار به دیوارهای سفارت فرانسه در کابل پناه می آورند؛ آخرین سنگر امن برای غربیها و بسیاری از مردم درمانده در این میان محمد بیدا (Mohamed Bida) فرمانده تیم امنیتی سفارت به همراه گروه کوچکی از نیروهایش مسئولیت خطیر حفاظت از این جمعیت وحشت زده را بر عهده میگیرد آنها باید در میان آشوب ترس و زمان رو به پایان صدها نفر را از دل خطر به فرودگاه برسانند: مأموریتی مرگبار که میتواند برای بسیاری تنها مسیر رسیدن به آزادی باشد",
        poster: "13.jpg",
        video:"13.mp4",
        genre: "Reality / Action",
        year: "2025",
        rate: "6.7",
        category: "action",
        featured: false,
        type: "movie",
      }
    ];
  
    // <<< NEW_MOVIES >>>
const NEW_MOVIES = [
      {
        id: 6,
        title: "The Price of Confession",
        desc: "در سریال بهای اعتراف آن یون سو معلم هنر ناگهان شوکه میشود وقتی شوهرش به قتل میرسد و او متهم اصلی این جنایت میگردد. زندگی اش وارونه میشود زندگی آرام اعتماد و امنیت خانوادگی اش با شک و اتهام جایگزین میشود ولی وقتی در زندان با مو آن زنی مرموز با اسراری تاریک دیدار میکند تلاشی خطرناک و پیچیده برای اثبات بی گناهی اش آغاز میگردد. او باید بین حقیقت و قربانی شدن یکی را انتخاب کند تصمیمی که نه فقط سرنوشت خودش بلکه عدالت حقیقت و زندگی کسانی که دوست دارد را رقم خواهد زد. ",
        poster: "ba.jpg",
        video:"ba.mp4",
        genre: "Thriller",
        year: "2024",
        rate: "7.6",
        category: "criminal",
       featured: false,
        type: "movie",
    },
      {
        id: 8,
        title: "Detective Kien: The Headless Horror",
        desc: "تریلری رازآلود",
        poster: "kar.jpg",
        video:"kar.mp4",
        genre: "ترسناک",
        year: "2025",
        rate: "7",
        category: "scary",
       featured: false,
        type: "movie",
    },
      {
        id: 9,
        title: "Five Nights at Freddy's 2",
        desc:"یک سال پس از کابوس فراطبیعی نخست در رستوران Freddy Fazbear's Pizza شهر تبدیل به محلی برای جشن فزفست شده الهام گرفته از داستانهای محلی درباره ترس و افسانه مایک نگهبان پیشین و ونسا مأمور پلیس تلاش دارند حقیقت را از خواهر یازده ساله مایک آبی که هنوز با انیماترونیکهای ترسناک آن رستوران ارتباط دارد. پنهان کنند",
        poster: "f.jpg",
        rate: "5.5",
        video:"f.mp4",
        genre: "ترسناک",
        year: "2025",
        category: "scary",
        featured: false,
        type: "movie",
      }
    ];

    // <<< SERIES >>>
const Series = [
      {
        id: 6,
        title: "The Price of Confession",
        desc: "در سریال بهای اعتراف آن یون سو معلم هنر ناگهان شوکه میشود وقتی شوهرش به قتل میرسد و او متهم اصلی این جنایت میگردد. زندگی اش وارونه میشود زندگی آرام اعتماد و امنیت خانوادگی اش با شک و اتهام جایگزین میشود ولی وقتی در زندان با مو آن زنی مرموز با اسراری تاریک دیدار میکند تلاشی خطرناک و پیچیده برای اثبات بی گناهی اش آغاز میگردد. او باید بین حقیقت و قربانی شدن یکی را انتخاب کند تصمیمی که نه فقط سرنوشت خودش بلکه عدالت حقیقت و زندگی کسانی که دوست دارد را رقم خواهد زد. ",
        poster: "ba.jpg",
        video:"ba.mp4",
        genre: "Thriller",
        year: "2024",
        rate: "7.6",
        category: "criminal",
        featured: false,
        type: "Series",
    },
      {
        id: 8,
        title: "Detective Kien: The Headless Horror",
        desc: "تریلری رازآلود",
        poster: "kar.jpg",
        video:"kar.mp4",
        genre: "ترسناک",
        year: "2025",
        rate: "7",
        category: "scary",
        featured: false,
        type: "Series",
    },
      {
        id: 9,
        title: "Five Nights at Freddy's 2",
        desc:"یک سال پس از کابوس فراطبیعی نخست در رستوران Freddy Fazbear's Pizza شهر تبدیل به محلی برای جشن فزفست شده الهام گرفته از داستانهای محلی درباره ترس و افسانه مایک نگهبان پیشین و ونسا مأمور پلیس تلاش دارند حقیقت را از خواهر یازده ساله مایک آبی که هنوز با انیماترونیکهای ترسناک آن رستوران ارتباط دارد. پنهان کنند",
        poster: "f.jpg",
        rate: "5.5",
        video:"f.mp4",
        genre: "ترسناک",
        year: "2025",
        rate: "5.5",
        category: "scary",
        featured: false,
        type: "Series",
      }
    ];
  
    // <<< SERIES >>>
const Anime = [
      {
        id: 6,
        title: "The Price of Confession",
        desc: "در سریال بهای اعتراف آن یون سو معلم هنر ناگهان شوکه میشود وقتی شوهرش به قتل میرسد و او متهم اصلی این جنایت میگردد. زندگی اش وارونه میشود زندگی آرام اعتماد و امنیت خانوادگی اش با شک و اتهام جایگزین میشود ولی وقتی در زندان با مو آن زنی مرموز با اسراری تاریک دیدار میکند تلاشی خطرناک و پیچیده برای اثبات بی گناهی اش آغاز میگردد. او باید بین حقیقت و قربانی شدن یکی را انتخاب کند تصمیمی که نه فقط سرنوشت خودش بلکه عدالت حقیقت و زندگی کسانی که دوست دارد را رقم خواهد زد. ",
        poster: "ba.jpg",
        video:"ba.mp4",
        genre: "Thriller",
        year: "2024",
        rate: "7.6",
        category: "criminal",
        featured: false,
        type: "Series",
    },
      {
        id: 8,
        title: "Detective Kien: The Headless Horror",
        desc: "تریلری رازآلود",
        poster: "kar.jpg",
        video:"kar.mp4",
        genre: "ترسناک",
        year: "2025",
        rate: "7",
        category: "scary",
        featured: false,
        type: "Series",
    },
      {
        id: 9,
        title: "Five Nights at Freddy's 2",
        desc:"یک سال پس از کابوس فراطبیعی نخست در رستوران Freddy Fazbear's Pizza شهر تبدیل به محلی برای جشن فزفست شده الهام گرفته از داستانهای محلی درباره ترس و افسانه مایک نگهبان پیشین و ونسا مأمور پلیس تلاش دارند حقیقت را از خواهر یازده ساله مایک آبی که هنوز با انیماترونیکهای ترسناک آن رستوران ارتباط دارد. پنهان کنند",
        poster: "f.jpg",
        rate: "5.5",
        video:"f.mp4",
        genre: "ترسناک",
        year: "2025",
        rate: "5.5",
        category: "scary",
        featured: false,
        type: "Series",
      }
    ];
  